version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      ASYNC_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/app_db
      SYNC_DATABASE_URL: postgresql://postgres:postgres@db:5432/app_db
      API_KEY: 12345
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 -m scripts.install_postgis && alembic upgrade head && python3 -m scripts.create_test_data &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
