"""add created_at, updated_at, is_deleted to all models

Revision ID: 95e8d8e0cbf7
Revises: 2133caca08ae
Create Date: 2025-10-23 10:58:23.892930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e8d8e0cbf7'
down_revision: Union[str, Sequence[str], None] = '2133caca08ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('activities', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('activities', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_activities_is_deleted'), 'activities', ['is_deleted'], unique=False)
    op.add_column('buildings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('buildings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('buildings', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index('idx_building_geom', 'buildings', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_buildings_is_deleted'), 'buildings', ['is_deleted'], unique=False)
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_column('organizations', 'is_deleted')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'created_at')
    op.drop_index(op.f('ix_buildings_is_deleted'), table_name='buildings')
    op.drop_index('idx_building_geom', table_name='buildings', postgresql_using='gist')
    op.drop_column('buildings', 'is_deleted')
    op.drop_column('buildings', 'updated_at')
    op.drop_column('buildings', 'created_at')
    op.drop_index(op.f('ix_activities_is_deleted'), table_name='activities')
    op.drop_column('activities', 'is_deleted')
    op.drop_column('activities', 'updated_at')
    op.drop_column('activities', 'created_at')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
